[project]
name = "das2py"
version = "3.0rc7"
dependencies = [ "numpy>=1.16.6", "lxml" ]
description = "An efficient space physics data client for python"
readme = "README.md"
# 2.7, or 3.6 and up
requires-python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"
license = "MIT"
authors = [
   {name = "C Piker", email = "cpiker@users.noreply.github.com"}
]
maintainers = [
	{name = "K Steele", email = "KaiwenS7@users.noreply.github.com"}
]
keywords = ["space-physics", "magnetosphere", "das2"]

[project.urls]
Homepage = "https://das2.org/das2py"
Repository = "https://github.com/das-developers/das2py"

[project.scripts]
das_verify = "das3.verify:main"
das_cdf_info = "das3.cdf:main"

[build-system]
#requires = [ "setuptools", "numpy>=2.0.0" ]
requires = [ "setuptools", "numpy>=1.16.0"]
build-backend = "setuptools.build_meta"

#[tool.setuptools]
#include-package-data = true
#packages = ["das3", "das3.pycdf", "das2", "_das3"]
