# Go generate the sha-hash run
# HASH=$(openssl sha256  das2C-${VERSION}.tar.gz | awk '{print $2}')
#
# Example:
#  openssl sha256 das2py-tmp.tar.gz | awk '{print $2}'

{% set name = "das2py" %}
{% set conda_version = "2.3.0" %}
{% set git_version = "2.3.0" %}
{% set bld_date = "20231108" %}
{% set sha256 = "a417f1f5bbb5af408cbf3ced8c2da007ed40964f3d0468e6f6f4af95e865ab48" %}

package:
   name: {{ name }} 
   version: {{ conda_version }} 
   
source:
   fn:  das2py-{{ git_version }}.tar.gz
   url: https://github.com/das-developers/das2py/archive/refs/tags/v{{ git_version }}.tar.gz
   sha256: {{ sha256 }}
   
build:
   # This is the zeroth build
   number: 0
   
# The build process for das2py calls python in the make files so we
# need to make sure it uses the anaconda python, not the system version

requirements:
   build:
      - {{ compiler('c') }}
      - setuptools
      - python
      - pip
      - wheel
      - numpy >=1.10.0 
      - das2c =={{ git_version }}
      - lxml

   host:
      - python
      - numpy >=1.10.0
      - das2c =={{ git_version }}
      - lxml

   run:
      - python
      - setuptools
      - numpy >=1.10.0
      - das2c =={{ git_version }}
      - lxml
      
test:
   imports:
      - das2
      - _das2

about:
   home: https://das2.org/das2py
   license: MIT
   license_file: LICENSE
   summary: An efficient space physics data client for python
