#!/usr/bin/env python3

import sys

# On windows & mac you can "pip install das2py" to get this.
#
# You'll also need the CDF library installed on your local
# computer to provide the backing dllcdf.dll/libcdf.so.  You
# can get it here:
#    https://cdf.gsfc.nasa.gov/html/sw_and_docs.html
# Get verision v3.9.

import das2.pycdf



f = das2.pycdf.CDF(sys.argv[1])

for k in f.attrs:
	print(k, "=", f.attrs[k])
	
print()

for k in f.keys():
	print(k)
	print(f[k])
	print(f[k].attrs)
	
	# Now print the first record
	print( f[k].shape)
	if len(f[k].shape) == 1:
		print( f[k][:] )
	else:
		if f[k].shape[0] > 0:
			print( f[k][0,:] )
	
	print()
	

